In [1]:
%matplotlib inline


Neural Networks
===============

Neural networks can be constructed using the ``torch.nn`` package.

Now that you had a glimpse of ``autograd``, ``nn`` depends on
``autograd`` to define models and differentiate them.
An ``nn.Module`` contains layers, and a method ``forward(input)`` that
returns the ``output``.

For example, look at this network that classifies digit images:

.. figure:: /_static/img/mnist.png
   :alt: convnet

   convnet

It is a simple feed-forward network. It takes the input, feeds it
through several layers one after the other, and then finally gives the
output.

A typical training procedure for a neural network is as follows:

- Define the neural network that has some learnable parameters (or
  weights)
- Iterate over a dataset of inputs
- Process input through the network
- Compute the loss (how far is the output from being correct)
- Propagate gradients back into the network’s parameters
- Update the weights of the network, typically using a simple update rule:
  ``weight = weight - learning_rate * gradient``

Define the network
------------------

Let’s define this network:



In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()


        # input channel이 1이고 output channel이 6인 3*3크기의 convolution layer를 준비한다.
        # 즉 3*3 크기의 1 layer를 갖는 convolution block 6개를 준비한다.
        self.conv1 = nn.Conv2d(1, 6, 3)

        # input channel이 6이고 output channel이 16인 3*3크기의 convolution layer를 준비한다.
        # 즉 3*3 크기의 6layer를 갖는 convolution block 16개를 준비한다.
        self.conv2 = nn.Conv2d(6, 16, 3)



        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120) #16*6*6 크기의 vector가 입력으로 들어가 120이 출력으로 나오는 fully connected layer를 준비한다
        self.fc2 = nn.Linear(120, 84) # 120 입력 --> 84 출력
        self.fc3 = nn.Linear(84, 10)  # 84 입력 --> 10 출력

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))   # x --> conv1 --> relu --> max_pooling
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)   # --> conv1 --> relu --> max_pooling
        x = x.view(-1, self.num_flat_features(x))    # -->flatten
        x = F.relu(self.fc1(x)) # --> fc1 --> relu
        x = F.relu(self.fc2(x)) # --> fc2 --> relu
        x = self.fc3(x)  # --> fc3
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


You just have to define the ``forward`` function, and the ``backward``
function (where gradients are computed) is automatically defined for you
using ``autograd``.
You can use any of the Tensor operations in the ``forward`` function.

The learnable parameters of a model are returned by ``net.parameters()``



In [7]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight
print(params[0][0])

10
torch.Size([6, 1, 3, 3])
tensor([[[-0.0174,  0.1163, -0.1692],
         [-0.2557,  0.2986, -0.1179],
         [-0.1837,  0.0715,  0.2124]]], grad_fn=<SelectBackward>)


In [9]:
for i in range(len(params)):
    print(f"{i} :{params[i].size()}")

0 :torch.Size([6, 1, 3, 3])
1 :torch.Size([6])
2 :torch.Size([16, 6, 3, 3])
3 :torch.Size([16])
4 :torch.Size([120, 576])
5 :torch.Size([120])
6 :torch.Size([84, 120])
7 :torch.Size([84])
8 :torch.Size([10, 84])
9 :torch.Size([10])


In [11]:
params[0][0], params[1]

tensor([[[-0.0174,  0.1163, -0.1692],
         [-0.2557,  0.2986, -0.1179],
         [-0.1837,  0.0715,  0.2124]]], grad_fn=<SelectBackward>)

Let's try a random 32x32 input.
Note: expected input size of this net (LeNet) is 32x32. To use this net on
the MNIST dataset, please resize the images from the dataset to 32x32.



In [10]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0139,  0.0864, -0.0364,  0.0478, -0.0333, -0.1364, -0.1002,  0.0169,
         -0.0914, -0.0341]], grad_fn=<AddmmBackward>)


Zero the gradient buffers of all parameters and backprops with random
gradients:



In [12]:
net.zero_grad()
out.backward(torch.randn(1, 10))

<div class="alert alert-info"><h4>Note</h4><p>``torch.nn`` only supports mini-batches. The entire ``torch.nn``
    package only supports inputs that are a mini-batch of samples, and not
    a single sample.

    For example, ``nn.Conv2d`` will take in a 4D Tensor of
    ``nSamples x nChannels x Height x Width``.

    If you have a single sample, just use ``input.unsqueeze(0)`` to add
    a fake batch dimension.</p></div>

Before proceeding further, let's recap all the classes you’ve seen so far.

**Recap:**
  -  ``torch.Tensor`` - A *multi-dimensional array* with support for autograd
     operations like ``backward()``. Also *holds the gradient* w.r.t. the
     tensor.
  -  ``nn.Module`` - Neural network module. *Convenient way of
     encapsulating parameters*, with helpers for moving them to GPU,
     exporting, loading, etc.
  -  ``nn.Parameter`` - A kind of Tensor, that is *automatically
     registered as a parameter when assigned as an attribute to a*
     ``Module``.
  -  ``autograd.Function`` - Implements *forward and backward definitions
     of an autograd operation*. Every ``Tensor`` operation creates at
     least a single ``Function`` node that connects to functions that
     created a ``Tensor`` and *encodes its history*.

**At this point, we covered:**
  -  Defining a neural network
  -  Processing inputs and calling backward

**Still Left:**
  -  Computing the loss
  -  Updating the weights of the network

Loss Function
-------------
A loss function takes the (output, target) pair of inputs, and computes a
value that estimates how far away the output is from the target.

There are several different
`loss functions <https://pytorch.org/docs/nn.html#loss-functions>`_ under the
nn package .
A simple loss is: ``nn.MSELoss`` which computes the mean-squared error
between the input and the target.

For example:



In [16]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
print("output: ", output.tolist())
print("target: ", target.tolist())
criterion = nn.MSELoss()

loss = criterion(output, target)
print("loss: ", loss)


output:  [[0.013891179114580154, 0.08642841875553131, -0.036352649331092834, 0.04783591628074646, -0.03329552337527275, -0.13644477725028992, -0.10021305829286575, 0.01690155453979969, -0.09137355536222458, -0.03406347334384918]]
target:  [[0.8694197535514832, -0.13299626111984253, -0.7334118485450745, 1.9200377464294434, 0.007024133112281561, 1.3938649892807007, -1.8798972368240356, -0.9474156498908997, 0.5212839245796204, 1.1237212419509888]]
loss:  tensor(1.2928, grad_fn=<MseLossBackward>)


Now, if you follow ``loss`` in the backward direction, using its
``.grad_fn`` attribute, you will see a graph of computations that looks
like this:

::

    input -> conv2d -> relu -> maxpool2d -> conv2d -> relu -> maxpool2d
          -> view -> linear -> relu -> linear -> relu -> linear
          -> MSELoss
          -> loss

So, when we call ``loss.backward()``, the whole graph is differentiated
w.r.t. the loss, and all Tensors in the graph that has ``requires_grad=True``
will have their ``.grad`` Tensor accumulated with the gradient.

For illustration, let us follow a few steps backward:



#### grad_fn 예제

In [17]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [18]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [19]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [23]:
y = x - 2
print(y)

tensor([[-1., -1.],
        [-1., -1.]], grad_fn=<SubBackward0>)


In [20]:
y = x * 2
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<MulBackward0>)


In [21]:
y = torch.tanh(x)
print(y)

tensor([[0.7616, 0.7616],
        [0.7616, 0.7616]], grad_fn=<TanhBackward>)


In [25]:
y = torch.cos(x)
print(y)
y = torch.sin(x)
print(y)

tensor([[0.5403, 0.5403],
        [0.5403, 0.5403]], grad_fn=<CosBackward>)
tensor([[0.8415, 0.8415],
        [0.8415, 0.8415]], grad_fn=<SinBackward>)


In [22]:
y = x**2
print(y)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)


Backprop
--------
To backpropagate the error all we have to do is to ``loss.backward()``.
You need to clear the existing gradients though, else gradients will be
accumulated to existing gradients.


Now we shall call ``loss.backward()``, and have a look at conv1's bias
gradients before and after the backward.



In [26]:
# 기본적으로 변화도는 backward() 함수를 호출할 때마다 buffer에 누적된다. 
# 따라서 반드시 다음과 같이 변화도를 0으로 만들어주는 작업을 해야 한다.
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0217,  0.0055,  0.0023,  0.0121, -0.0155, -0.0135])


Now, we have seen how to use loss functions.

**Read Later:**

  The neural network package contains various modules and loss functions
  that form the building blocks of deep neural networks. A full list with
  documentation is `here <https://pytorch.org/docs/nn>`_.

**The only thing left to learn is:**

  - Updating the weights of the network

Update the weights
------------------
The simplest update rule used in practice is the Stochastic Gradient
Descent (SGD):

     ``weight = weight - learning_rate * gradient``

We can implement this using simple Python code:

.. code:: python

    learning_rate = 0.01
    for f in net.parameters():
        f.data.sub_(f.grad.data * learning_rate)

However, as you use neural networks, you want to use various different
update rules such as SGD, Nesterov-SGD, Adam, RMSProp, etc.
To enable this, we built a small package: ``torch.optim`` that
implements all these methods. Using it is very simple:



In [27]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

.. Note::

      Observe how gradient buffers had to be manually set to zero using
      ``optimizer.zero_grad()``. This is because gradients are accumulated
      as explained in the `Backprop`_ section.

